---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: onepassword
spec:
  interval: 15m
  ref:
    tag: 2.4.2
    digest: sha256:c0e87d231e5b082ad39bda4f3f0890a9923fe5d70694cadc4f7b4cc0f9df6c0c
  url: oci://ghcr.io/1password/connect
  