---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: onepassword
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.4.0
    digest: sha256:c659ad44096c24db423b3cd428433296f56d3c1d1eadb7a13c9da15a58dc80a8
  url: oci://ghcr.io/1password/connect
  