---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
  ref:
    # TODO: confirm this is a real version that is behind latest.
    tag: 0.28.2
    digest: sha256:484e812908daeac1b84614df333040ffe2eb868f3a7169ffe6c003d566f554e6
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
    namespace: flux-system